SELECT * FROM SM2ITEM I WHERE CONTAINS(I.ITEMNAME,'ARM');

WITH BASEQ AS (
SELECT NYSE.NYSE_DATE AS DATE, S2ITEM.ITEMNAME, S2ARM.*  
FROM SYLVINA.DBO.NYSE_DATES NYSE
JOIN SM2DARMAAM S2ARM ON DATE BETWEEN S2ARM.STARTDATE AND S2ARM.ENDDATE
JOIN SM2ITEM S2ITEM ON S2ARM.ITEM = S2ITEM.ITEM
JOIN SM2DINFO DINFO ON DINFO.SECID = S2ARM.SECID 
WHERE S2ARM.SECID = 9807  AND S2ARM.ITEM IN ( 36, 37, 44, 45, 46, 47, 48 )
ORDER BY DATE ASC ),

BASEQ2 AS (
SELECT X.DATE,
CASE WHEN X.ITEM = 36 THEN X.VALUE_ ELSE NULL END AS CRANK,
CASE WHEN X.ITEM = 37 THEN X.VALUE_ ELSE NULL END AS REGRANK_D,
CASE WHEN X.ITEM = 44 THEN X.VALUE_ ELSE NULL END AS ARM_SCORE, // Good one
CASE WHEN X.ITEM = 45 THEN X.VALUE_ ELSE NULL END AS GLOBAL_RANK,
CASE WHEN X.ITEM = 46 THEN X.VALUE_ ELSE NULL END AS ARM_PREF,
CASE WHEN X.ITEM = 47 THEN X.VALUE_ ELSE NULL END AS ARM_REC,
CASE WHEN X.ITEM = 48 THEN X.VALUE_ ELSE NULL END AS ARM_REV
FROM BASEQ X)

SELECT DATE, MAX(CRANK), MAX(REGRANK_D), MAX(ARM_SCORE), MAX(GLOBAL_RANK), MAX(ARM_PREF), MAX(ARM_REC), MAX(ARM_REV) from BASEQ2 Y
GROUP BY Y.DATE;