-- Main view to aggregate north american pricing data
CREATE OR REPLACE VIEW SYLVINA.DBO.VW_DS2PRICING AS
	WITH
	ADJFACTOR AS (
		SELECT 
			INFOCODE,
			ADJTYPE,
			ADJDATE,
			COALESCE(ENDADJDATE,'3000-01-01') AS ENDADJDATE,
			CUMADJFACTOR
		FROM QAI.DBO.DS2ADJ
		UNION ALL
		SELECT
			INFOCODE,
			0 AS ADJTYPE,
			MIN(ADJDATE) AS ADJDATE,
			'3000-01-01' AS ENDADJDATE,
			1 AS CUMADJFACTOR
		FROM QAI.DBO.DS2ADJ 
		GROUP BY INFOCODE
	),

	ALLEXCHPRICING AS (
		SELECT * , 'Y' AS PRIMEXCH FROM QAI.DBO.DS2PRIMQTPRC UNION ALL SELECT *, 'N' AS PRIMEXCH FROM QAI.DBO.DS2SCDQTPRC
	)

	SELECT 
		SMX.ID,
		D.MARKETDATE,
		--CASE
		--	WHEN X.ALTDSCODE IS NOT NULL THEN X.ALTDSCODE ELSE I.DSCODE
		--END AS DSCODE,

		CASE WHEN X.PRICEUNIT = 'E-02' THEN (D.OPEN_*A.CUMADJFACTOR)/100 
				ELSE D.OPEN_*A.CUMADJFACTOR END AS OPEN_,
		CASE WHEN X.PRICEUNIT = 'E-02' THEN (D.HIGH*A.CUMADJFACTOR)/100 
			ELSE D.HIGH*A.CUMADJFACTOR END AS HIGH,
		CASE WHEN X.PRICEUNIT = 'E-02' THEN (D.LOW*A.CUMADJFACTOR)/100 
			ELSE D.LOW*A.CUMADJFACTOR END AS LOW,
		CASE WHEN X.PRICEUNIT = 'E-02' THEN (D.CLOSE_*A.CUMADJFACTOR)/100 
			ELSE D.CLOSE_*A.CUMADJFACTOR END AS CLOSE_,
		--CASE WHEN X.PRICEUNIT = 'E-02' THEN (D.BID*A.CUMADJFACTOR)/100 
		--	ELSE D.BID*A.CUMADJFACTOR END AS BID,
		--CASE WHEN X.PRICEUNIT = 'E-02' THEN (D.ASK*A.CUMADJFACTOR)/100 
		--	ELSE D.ASK*A.CUMADJFACTOR END AS ASK,
		--CASE WHEN X.PRICEUNIT = 'E-02' THEN (D.VWAP*A.CUMADJFACTOR)/100 
		--	ELSE D.VWAP*A.CUMADJFACTOR END AS VWAP,
		D.VOLUME/A.CUMADJFACTOR AS VOLUME,
		--D.CONSOLVOL/A.CUMADJFACTOR AS CONSOLVOL,
		D.ISOCURRCODE AS CURRENCY,
        D.EXCHINTCODE,
		D.PRIMEXCH AS ISPRIMEXCHQT,
		M.EXCHNAME,
		A.ADJTYPE,
		A.CUMADJFACTOR,
		X.PRICEUNIT AS PRICEUNITADJUSTMENT,
        SMX.SECCODE,
		D.INFOCODE,
        SX.RANK
        
	FROM ALLEXCHPRICING D
		JOIN ADJFACTOR A
			ON	A.INFOCODE = D.INFOCODE
			AND	D.MARKETDATE BETWEEN A.ADJDATE AND A.ENDADJDATE
		JOIN QAI.DBO.DS2EXCHQTINFO X
			ON	X.INFOCODE = D.INFOCODE
			AND	X.EXCHINTCODE = D.EXCHINTCODE
		JOIN QAI.DBO.DS2EXCHANGE M
			ON	M.EXCHINTCODE = X.EXCHINTCODE
		JOIN QAI.DBO.DS2CTRYQTINFO I
			ON	I.INFOCODE = D.INFOCODE
		JOIN QAI.DBO.SECMAPX SX
			ON SX.VENTYPE = 33 and SX.VENCODE = I.INFOCODE 
		JOIN QAI.DBO.SECMSTRX SMX 
			ON SMX.SECCODE = SX.SECCODE and SMX.TYPE_ =1 AND D.MARKETDATE BETWEEN 
                            IFNULL(SX.STARTDATE,DATE('1970-01-01'))
                            AND IFNULL(SX.ENDDATE,DATE('3000-01-01'))
            QUALIFY ROW_NUMBER() OVER (PARTITION BY SMX.ID, D.MARKETDATE, ISPRIMEXCHQT,ADJTYPE ORDER BY RANK ASC) = 1;

    ;


// Create Sylvina Liquid Universe
CREATE OR REPLACE TABLE SYLVINA.DBO.LIQUID_RANK AS
(
WITH BASEQ AS
(
SELECT  
    DS.ID,
    YEAR(DS.MARKETDATE) AS MYEAR,
    MEDIAN(DS.CLOSE_*DS.VOLUME) AS LIQUID_MEDIAN,
    SUM(DS.CLOSE_*DS.VOLUME) AS LIQUID_SUM
FROM SYLVINA.DBO.VW_DS2PRICING DS
WHERE
DS.ADJTYPE=1 AND
DS.ISPRIMEXCHQT='Y' AND
DS.MARKETDATE BETWEEN DATE('1990-01-01') AND DATE('2023-12-31')
GROUP BY DS.ID, MYEAR
HAVING LIQUID_MEDIAN IS NOT NULL 
ORDER BY MYEAR, LIQUID_MEDIAN, LIQUID_SUM DESC
)
SELECT X.ID,
       Y.NAME,
       Y.COUNTRY,
       X.MYEAR,
       ROW_NUMBER() OVER (PARTITION BY X.MYEAR ORDER BY X.LIQUID_MEDIAN DESC) AS LIQUID_RANK,
       CAST((X.LIQUID_SUM/1000000) AS NUMBER(38,0)) AS LIQUID_SUM
 FROM BASEQ X 
 JOIN SECMSTRX Y ON X.ID = Y.ID 
 QUALIFY LIQUID_RANK < 1500
);


-- QUERY MY DATABASE

--Example query 

SELECT * FROM SYLVINA.DBO.VW_DS2PRICING 
WHERE ID = 'ASKJ' 
--MARKETDATE < DATE('1995-01-01') 
AND ADJTYPE=2 AND
ISPRIMEXCHQT='Y'
 ORDER BY MARKETDATE ASC;


-- Creates coverage summary for Sylvina universe 
WITH BASEQ AS (
SELECT 
    DISTINCT(P.ID),
    UI.NAME,
    MIN(P.MARKETDATE) OVER (PARTITION BY P.ID) as START_DATE,
    MAX(P.MARKETDATE) OVER (PARTITION BY P.ID) as END_DATE,
    COUNT(P.CLOSE_) OVER (PARTITION BY P.ID) as VALUE_COUNT
FROM SYLVINA.DBO.VW_DS2PRICING P 
JOIN (SELECT DISTINCT(ID), NAME FROM SYLVINA.DBO.UNIVERSE_INFO) UI ON  UI.ID = P.ID
WHERE P.ADJTYPE =2 AND P.ISPRIMEXCHQT='Y'
)
SELECT Q.*,
        (SELECT COUNT(*) FROM SYLVINA.DBO.NYSE_DATES D_ WHERE D_.MARKETDATE BETWEEN START_DATE AND END_DATE) AS NYSE_DAYS,
        (VALUE_COUNT / NYSE_DAYS) AS DENSITY
 FROM BASEQ Q 
WHERE  ID IN (SELECT DISTINCT(ID) FROM SYLVINA.DBO.UNIVERSE_INFO);

CREATE VIEW SYLVINA.DBO.SECMAPXX AS
(
    SELECT SM.ID, SX.* 
    FROM QAI.DBO.SECMAPX SX
    JOIN QAI.DBO.SECMSTRX SM ON SX.SECCODE = SM.SECCODE AND SM.TYPE_=1
);

SELECT 
    ID,
    COUNT(VENTYPE) OVER (PARTITION BY ID) AS PRICING_SERIES,
    RANK,
    STARTDATE,
    ENDDATE
FROM SYLVINA.DBO.SECMAPXX 
WHERE VENTYPE=33 
ORDER BY PRICING_SERIES DESC, ID DESC, RANK ASC;

SELECT S.NAME, SXX.* FROM SYLVINA.DBO.SECMAPXX SXX 
JOIN SECMSTRX S ON S.SECCODE = SXX.SECCODE AND S.TYPE_=1
WHERE SXX.ID = 'ASKJ' and SXX.VENTYPE=33;

SELECT * FROM SECMSTRX SM 
JOIN SECMAPX SX ON SX.SECCODE = SM.SECCODE AND SM.TYPE_ = 1
WHERE SM.ID = 'ASKJ';

SELECT * FROM SYLVINA.DBO.SECMAPXX WHERE ID = 'MSFT' AND VENTYPE = 33;

SELECT * FROM SYLVINA.DBO.UNIV_INFO WHERE ID = 'GGC';
SELECT * FROM SYLVINA.DBO.VW_DS2PRICING WHERE ID='THLLY' AND ISPRIMEXCHQT='Y' AND ADJTYPE=2 ORDER BY MARKETDATE ASC;

SELECT DISTINCT(ID) FROM SYLVINA.DBO.UNIV_INFO;

SELECT * FROM SECMSTRX WHERE  ID = '000001NL';


SELECT ID, NAME, MYEAR, LIQUID_RANK FROM SYLVINA.DBO.LIQUID_RANK 
WHERE CONTAINS(NAME,UPPER('VISA INC'))
ORDER BY MYEAR ASC;

SELECT DISTINCT * FROM SYLVINA.DBO.LIQUID_RANK WHERE MYEAR = 2022 and LIQUID_RANK>1000;

